# Generated by Django 3.2.20 on 2023-07-07 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('image_key', models.CharField(max_length=100)),
                ('etag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.UUID('00bfe68a-06eb-4453-80c7-9b1a62c6e14e'), editable=False)),
                ('engineNumber', models.CharField(max_length=100)),
                ('chassisNumber', models.CharField(max_length=100)),
                ('registrationNumber', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inspection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
