# Generated by Django 3.2.20 on 2023-07-07 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='type',
            new_name='extension',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('89d7194d-c513-4991-bb01-2e0075349294'), editable=False),
        ),
    ]
