# Generated by Django 3.2.20 on 2023-07-07 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20230707_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('068f61b9-8774-4894-bf31-3339e7f97db1'), editable=False),
        ),
    ]
